on:
  push:
    branches:
      - master
      - main
jobs:
  preveri_teste:
    runs-on: ubuntu-latest
    steps:
      - name: Preveri testne datoteke
        uses: actions/checkout@v2
      - name: Preveri kodo
        run: |
          if [ ! -f "../../test.cpp" ] || [ ! -f "../../main.cpp" ]; then
            echo "Manjkajoči testni datoteki!" >&2
            exit 1
          fi

  izvedi_teste:
    dependsOn: preveri_teste
    runs-on: ubuntu-latest
    condition: always() # Vedno se izvede, tudi če je prejšnji posel spodletel
    steps:
      - name: Kompilacija in izvedba testov
        run: |
          if [ -s "napaka.txt" ]; then
            echo "Napaka v prejšnjem poslu, testi se ne bodo izvedli."
            exit 1
          fi
          cd ../../
          g++ test.cpp main.cpp -o test_program
          ./test_program
        