on:
  push:
    branches:
      - master
      - main
jobs:
  preveri_teste:
    runs-on: ubuntu-latest
    steps:
      - name: Preveri testne datoteke
        uses: actions/checkout@v2
      - name: Preveri kodo
        run: |
          if [ ! -f "test.cpp" ] || [ ! -f "main.cpp" ]; then
            echo "Manjkajoči testni datoteki!" >&2
            echo "1" > napaka.txt
          else
            echo "0" > napaka.txt
          fi
      - name: Ustvari artefakt
        uses: actions/upload-artifact@v2
        with:
          name: napaka
          path: napaka.txt

  izvedi_teste:
    needs: preveri_teste
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Prenesi artefakt
        uses: actions/download-artifact@v2
        with:
          name: napaka
      - name: Preberi napaka.txt
        run: |
          napaka=$(<napaka.txt)
          if [ $napaka -eq 0 ]; then
            echo "Ni napake"
          else
            echo "Napaka: Manjkajoči testni datoteki!"
            exit 1
          fi
      - uses: actions/checkout@v2
      - name: Kompilacija in izvedba testov
        
        run: |
          g++ test.cpp main.cpp -o test_program
          ./test_program
        