name: deploy

#izvede se, ko se zakljuci workflow test
on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed

jobs:
  deploy_to_dockerhub:
    runs-on: [self-hosted, linux, x64]
    #izvede se samo ce je job ki je pognal ta workflow uspesno zakljucen
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          sudo docker build -t zalozniktine/radex:latest . #. pomeni da je v trenutnem direkoriju dockerfile
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push Docker image to DockerHub
        run: |
          sudo docker push zalozniktine/radex:latest
