name: test

on:
  push:
    branches:
      - master
      - main

jobs:
  preveri_teste:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Preveri testne datoteke
        uses: actions/checkout@v2
      - name: Preveri kodo
        run: |
          if [ ! -f "test.cpp" ] || [ ! -f "main.cpp" ]; then #preverim ce obstajata testni datoteki
            echo "Manjkajoči testni datoteki!" >&2
            echo "1" > napaka.txt #ce manjkata, v file dam 0
          else
            echo "0" > napaka.txt #ce obstajata, v file dam 1
          fi
      - name: Ustvari artefakt #ustvarim artefakt
        uses: actions/upload-artifact@v2
        with:
          name: napaka
          path: napaka.txt

  izvedi_teste:
    needs: preveri_teste
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [self-hosted]
        compiler: [g++, clang++]
    if: always() #v vsakem primeru se izvede ne glede na preveri_teste
    steps:
      - name: Prenesi artefakt
        uses: actions/download-artifact@v2
        with:
          name: napaka
      - name: Preberi napaka.txt
        run: |
          napaka=$(<napaka.txt) #preberem ce je napaka v .txt
          if [ $napaka -eq 0 ]; then
            echo "Ni napake"
          else
            echo "Napaka: Manjkajoči testni datoteki!"
            exit 1
          fi
      - uses: actions/checkout@v2
      - name: Kompilacija in izvedba testov
        run: |
          ${{ matrix.compiler }} test.cpp main.cpp -o test_program #uporabi matrix compiler
          ./test_program
        