name: Deploy docker

on:
  workflow_run:
    workflows: ["27141_test.yml"]
    types:
      - completed

jobs:
  deploy_to_dockerhub:
    runs-on: [self-hosted, linux, x64]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t zalozniktine/radex:latest .
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push Docker image to DockerHub
        run: |
          docker push zalozniktine/radex:latest
